In [65]:
# AI-Based Recruitment Screening Lab
# ---------------------------------
# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Step 2: Create synthetic candidate dataset
data = {
    "Name": [f"Candidate_{i}" for i in range(1, 21)],
    "Skills": [
        "Python, Data Analysis, Machine Learning",
        "Java, Spring Boot, Microservices",
        "Excel, HR Analytics, Employee Engagement",
        "SQL, Tableau, Data Visualization",
        "Python, Pandas, NumPy",
        "Project Management, Agile, Scrum",
        "Digital Marketing, SEO, Content Writing",
        "C++, Embedded Systems, IoT",
        "Finance, Accounting, Risk Management",
        "Cloud Computing, AWS, DevOps",
        "Python, NLP, Deep Learning",
        "JavaScript, React, Node.js",
        "HR Policies, Recruitment, Training",
        "Business Strategy, Consulting, Analytics",
        "Python, Statistics, Data Science",
        "Cybersecurity, Networking, Ethical Hacking",
        "Healthcare Management, Research, Analytics",
        "AI, Machine Learning, TensorFlow",
        "Marketing, Sales, CRM",
        "Python, SQL, Power BI"
    ],
    "Experience": np.random.randint(1, 10, 20),  # years of experience
    "Education": [
        "MBA", "B.Tech", "MBA", "B.Sc", "M.Sc", "MBA", "BBA", "B.Tech", "MBA", "B.Tech",
        "M.Tech", "B.Sc", "MBA", "MBA", "M.Sc", "B.Tech", "MBA", "M.Tech", "BBA", "M.Sc"
    ],
    "Certifications": [
        "Data Science", "Java Developer", "HR Analytics", "Tableau", "Python", "PMP",
        "Digital Marketing", "IoT", "Finance", "AWS", "Deep Learning", "Web Development",
        "HR", "Consulting", "Statistics", "Cybersecurity", "Healthcare", "AI", "Sales", "Power BI"
    ]
}

df = pd.DataFrame(data)

# Step 3: Define job description
job_description = """
We are looking for a Data Scientist with strong skills in Python, Machine Learning,
Data Analysis, and experience with tools like Pandas, NumPy, and Power BI.
An MBA or M.Sc in a relevant field is preferred. Certifications in Data Science or AI are a plus.
"""

# Step 4: TF-IDF + Cosine Similarity
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df["Skills"].tolist() + [job_description])
cosine_sim = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1]).flatten()
df["Similarity"] = cosine_sim

# Step 5: Weighted Scoring Model
def weighted_score(row):
    score = 0
    # Similarity weight
    score += row["Similarity"] * 0.5
    # Experience weight
    score += (row["Experience"] / 10) * 0.2
    # Education weight
    if row["Education"] in ["MBA", "M.Sc", "M.Tech"]:
        score += 0.2
    # Certification weight
    if row["Certifications"] in ["Data Science", "AI", "Deep Learning", "Python"]:
        score += 0.1
    return score

df["Final_Score"] = df.apply(weighted_score, axis=1)

# Step 6: Shortlist top candidates
shortlist = df.sort_values(by="Final_Score", ascending=False).head(5)

# Step 7: Display results
print("Top Candidates Shortlist:\n")
print(shortlist[["Name", "Skills", "Experience", "Education", "Certifications", "Final_Score"]])

Top Candidates Shortlist:

            Name                                   Skills  Experience Education Certifications  Final_Score
0    Candidate_1  Python, Data Analysis, Machine Learning           1       MBA   Data Science     0.477021
4    Candidate_5                    Python, Pandas, NumPy           3      M.Sc         Python     0.454316
10  Candidate_11               Python, NLP, Deep Learning           5    M.Tech  Deep Learning     0.436763
19  Candidate_20                    Python, SQL, Power BI           7      M.Sc       Power BI     0.419774
17  Candidate_18         AI, Machine Learning, TensorFlow           2    M.Tech             AI     0.416492

In [66]:
# This cell imports all the libraries required in the lab.
# pandas is used for working with tabular data.
# numpy is used for numerical operations.
# sklearn is used for text vectorization and similarity calculation.

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# This line improves the display of tables in notebooks.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

In [67]:
import pandas as pd
import numpy as np

# Step 1: Create Synthetic Recruitment Dataset
data = {
    "Candidate_ID": [f"C{i:03d}" for i in range(1, 21)],
    "Name": [f"Candidate_{i}" for i in range(1, 21)],
    "Skills": [
        "Python, Data Analysis, Machine Learning",
        "Java, Spring Boot, Microservices",
        "Excel, HR Analytics, Employee Engagement",
        "SQL, Tableau, Data Visualization",
        "Python, Pandas, NumPy",
        "Project Management, Agile, Scrum",
        "Digital Marketing, SEO, Content Writing",
        "C++, Embedded Systems, IoT",
        "Finance, Accounting, Risk Management",
        "Cloud Computing, AWS, DevOps",
        "Python, NLP, Deep Learning",
        "JavaScript, React, Node.js",
        "HR Policies, Recruitment, Training",
        "Business Strategy, Consulting, Analytics",
        "Python, Statistics, Data Science",
        "Cybersecurity, Networking, Ethical Hacking",
        "Healthcare Management, Research, Analytics",
        "AI, Machine Learning, TensorFlow",
        "Marketing, Sales, CRM",
        "Python, SQL, Power BI"
    ],
    "Years_of_Experience": np.random.randint(1, 11, 20),  # Random 1–10 years
    "Education": [
        "MBA", "B.Tech", "MBA", "B.Sc", "M.Sc", "MBA", "BBA", "B.Tech", "MBA", "B.Tech",
        "M.Tech", "B.Sc", "MBA", "MBA", "M.Sc", "B.Tech", "MBA", "M.Tech", "BBA", "M.Sc"
    ],
    "Certifications": [
        "Data Science", "Java Developer", "HR Analytics", "Tableau", "Python", "PMP",
        "Digital Marketing", "IoT", "Finance", "AWS", "Deep Learning", "Web Development",
        "HR", "Consulting", "Statistics", "Cybersecurity", "Healthcare", "AI", "Sales", "Power BI"
    ]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display first few rows
print(df.head())

  Candidate_ID         Name                                    Skills  Years_of_Experience Education  Certifications
0         C001  Candidate_1   Python, Data Analysis, Machine Learning                    2       MBA    Data Science
1         C002  Candidate_2          Java, Spring Boot, Microservices                    9    B.Tech  Java Developer
2         C003  Candidate_3  Excel, HR Analytics, Employee Engagement                    5       MBA    HR Analytics
3         C004  Candidate_4          SQL, Tableau, Data Visualization                    2      B.Sc         Tableau
4         C005  Candidate_5                     Python, Pandas, NumPy                    5      M.Sc          Python

In [68]:
# This cell creates a synthetic dataset of 20 candidates.
# Each row represents one candidate.
# The fields are designed to simulate basic recruitment information.

data = [
    {"candidate_id": 1, "name": "Aarav", "skills": "python sql machine learning excel", "experience_years": 3, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 2, "name": "Diya", "skills": "excel communication recruitment onboarding", "experience_years": 4, "education": "MBA HR", "certifications": 1},
    {"candidate_id": 3, "name": "Kabir", "skills": "python pandas data analysis sql tableau", "experience_years": 2, "education": "B.Sc", "certifications": 3},
    {"candidate_id": 4, "name": "Ishita", "skills": "java sql spring communication teamwork", "experience_years": 5, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 5, "name": "Vivaan", "skills": "python sql deep learning nlp bert", "experience_years": 6, "education": "M.Tech", "certifications": 4},
    {"candidate_id": 6, "name": "Anaya", "skills": "recruitment sourcing interview screening communication", "experience_years": 3, "education": "MBA HR", "certifications": 2},
    {"candidate_id": 7, "name": "Reyansh", "skills": "python sql power bi excel statistics", "experience_years": 4, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 8, "name": "Myra", "skills": "machine learning python data visualization tableau", "experience_years": 2, "education": "M.Sc", "certifications": 3},
    {"candidate_id": 9, "name": "Arjun", "skills": "manual testing selenium jira communication", "experience_years": 5, "education": "BCA", "certifications": 1},
    {"candidate_id": 10, "name": "Siya", "skills": "python sql ml nlp communication teamwork", "experience_years": 3, "education": "MCA", "certifications": 3},
    {"candidate_id": 11, "name": "Krish", "skills": "excel sql reporting dashboard power bi", "experience_years": 2, "education": "B.Com", "certifications": 2},
    {"candidate_id": 12, "name": "Aadhya", "skills": "python r statistics machine learning", "experience_years": 4, "education": "M.Stat", "certifications": 3},
    {"candidate_id": 13, "name": "Advik", "skills": "project management agile scrum communication", "experience_years": 6, "education": "MBA", "certifications": 2},
    {"candidate_id": 14, "name": "Kiara", "skills": "python sql data analysis recruitment hr analytics", "experience_years": 5, "education": "MBA HR", "certifications": 4},
    {"candidate_id": 15, "name": "Atharv", "skills": "c++ algorithms data structures problem solving", "experience_years": 1, "education": "B.Tech", "certifications": 1},
    {"candidate_id": 16, "name": "Navya", "skills": "python sql tableau power bi communication", "experience_years": 3, "education": "BBA", "certifications": 2},
    {"candidate_id": 17, "name": "Rudra", "skills": "nlp bert transformers python machine learning", "experience_years": 5, "education": "M.Tech", "certifications": 4},
    {"candidate_id": 18, "name": "Sara", "skills": "recruitment analytics excel communication hr operations", "experience_years": 4, "education": "MBA HR", "certifications": 2},
    {"candidate_id": 19, "name": "Vihaan", "skills": "python sql statistics data cleaning pandas", "experience_years": 2, "education": "B.Sc", "certifications": 2},
    {"candidate_id": 20, "name": "Meera", "skills": "python machine learning sql communication dashboards", "experience_years": 4, "education": "MCA", "certifications": 3}
]

df = pd.DataFrame(data)

print("Synthetic dataset created successfully.")
df

Synthetic dataset created successfully.

    candidate_id     name                                             skills  experience_years education  certifications
0              1    Aarav                  python sql machine learning excel                 3    B.Tech               2
1              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1
2              3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3
3              4   Ishita             java sql spring communication teamwork                 5    B.Tech               2
4              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4
5              6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2
6              7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2
7              8     Myra  machine learning python data visualization tab...                 2      M.Sc               3
8              9    Arjun         manual testing selenium jira communication                 5       BCA               1
9             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3
10            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2
11            12   Aadhya               python r statistics machine learning                 4    M.Stat               3
12            13    Advik       project management agile scrum communication                 6       MBA               2
13            14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4
14            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1
15            16    Navya          python sql tableau power bi communication                 3       BBA               2
16            17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4
17            18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2
18            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2
19            20    Meera  python machine learning sql communication dash...                 4       MCA               3

In [69]:
# Step 2: Check Dataset Shape and Columns

# Display number of rows and columns
print("Dataset Shape (rows, columns):", df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns)

# Optional: More readable format
print("\nNumber of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

# Convert columns to list (clean view)
print("\nColumns List:")
print(list(df.columns))

Dataset Shape (rows, columns): (20, 6)

Column Names:
Index(['candidate_id', 'name', 'skills', 'experience_years', 'education', 'certifications'], dtype='object')

Number of Rows: 20
Number of Columns: 6

Columns List:
['candidate_id', 'name', 'skills', 'experience_years', 'education', 'certifications']

In [70]:
# This cell checks the shape of the dataset and displays all column names.
# shape gives the total number of rows and columns.
# columns gives the names of all variables.

print("Dataset shape:", df.shape)
print("Column names:", list(df.columns))

Dataset shape: (20, 6)
Column names: ['candidate_id', 'name', 'skills', 'experience_years', 'education', 'certifications']

In [71]:
# Step 3: Preview the Dataset

# Display first 5 rows
print("First 5 rows of the dataset:")
print(df.head())

# Display last 5 rows
print("\nLast 5 rows of the dataset:")
print(df.tail())

# Display random sample (optional)
print("\nRandom sample from dataset:")
print(df.sample(5))

First 5 rows of the dataset:
   candidate_id    name                                      skills  experience_years education  certifications
0             1   Aarav           python sql machine learning excel                 3    B.Tech               2
1             2    Diya  excel communication recruitment onboarding                 4    MBA HR               1
2             3   Kabir     python pandas data analysis sql tableau                 2      B.Sc               3
3             4  Ishita      java sql spring communication teamwork                 5    B.Tech               2
4             5  Vivaan           python sql deep learning nlp bert                 6    M.Tech               4

Last 5 rows of the dataset:
    candidate_id    name                                             skills  experience_years education  certifications
15            16   Navya          python sql tableau power bi communication                 3       BBA               2
16            17   Rudra      nlp bert transformers python machine learning                 5    M.Tech               4
17            18    Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2
18            19  Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2
19            20   Meera  python machine learning sql communication dash...                 4       MCA               3

Random sample from dataset:
    candidate_id     name                                             skills  experience_years education  certifications
2              3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3
6              7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2
17            18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2
9             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3
14            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1

In [72]:
# This cell displays the first 5 rows of the dataset.
# head() is useful for quickly checking whether the data looks correct.

df.head()

   candidate_id    name                                      skills  experience_years education  certifications
0             1   Aarav           python sql machine learning excel                 3    B.Tech               2
1             2    Diya  excel communication recruitment onboarding                 4    MBA HR               1
2             3   Kabir     python pandas data analysis sql tableau                 2      B.Sc               3
3             4  Ishita      java sql spring communication teamwork                 5    B.Tech               2
4             5  Vivaan           python sql deep learning nlp bert                 6    M.Tech               4

In [73]:
# Step 4: Define the Job Description

# Create a sample job description for an AI/Data role
job_description = """
We are looking for a Data Analyst / AI Specialist with the following skills:
- Strong knowledge of Python and SQL
- Experience with Machine Learning algorithms
- Familiarity with Data Analysis and Visualization (Pandas, NumPy, Matplotlib)
- Understanding of AI concepts and model building
- Good communication and problem-solving skills
"""

# Display the job description
print("Job Description:\n")
print(job_description)

Job Description:


We are looking for a Data Analyst / AI Specialist with the following skills:
- Strong knowledge of Python and SQL
- Experience with Machine Learning algorithms
- Familiarity with Data Analysis and Visualization (Pandas, NumPy, Matplotlib)
- Understanding of AI concepts and model building
- Good communication and problem-solving skills

In [74]:
# This cell defines the target job description.
# In a real recruitment system, this text would come from an actual job posting.
# We keep it short and relevant for learning purposes.

job_description = "python sql machine learning nlp communication dashboards recruitment analytics"

print("Job Description:")
print(job_description)

Job Description:
python sql machine learning nlp communication dashboards recruitment analytics

In [75]:
# Step 5: Convert Text into Numerical Form Using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

# Combine candidate skills and job description into one list
documents = df["skills"].tolist() + [job_description]

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = vectorizer.fit_transform(documents)

# Display the shape of the TF-IDF matrix
print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

# Optional: Show feature names (words extracted)
print("\nSample Features (words):", vectorizer.get_feature_names_out()[:20])

TF-IDF Matrix Shape: (21, 46)

Sample Features (words): ['agile' 'algorithms' 'analysis' 'analytics' 'bert' 'bi' 'cleaning'
 'communication' 'dashboard' 'dashboards' 'data' 'deep' 'excel' 'hr'
 'interview' 'java' 'jira' 'learning' 'machine' 'management']

In [76]:
# This cell combines the job description and all candidate skills into one list.
# Then it converts the text into a TF-IDF matrix.
# The matrix is a numerical representation of the text.

documents = [job_description] + df["skills"].tolist()

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (21, 46)

In [77]:
# Step 6: Calculate Cosine Similarity

from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity between job description (last row) and all candidate skill rows
cosine_sim = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1]).flatten()

# Add similarity scores to the dataset
df["Cosine_Similarity"] = cosine_sim

# Display top 5 candidates based on similarity
print("Top 5 Candidates by Cosine Similarity:\n")
print(df[["candidate_id", "name", "skills", "Cosine_Similarity"]].sort_values(by="Cosine_Similarity", ascending=False).head())

Top 5 Candidates by Cosine Similarity:

    candidate_id   name                                             skills  Cosine_Similarity
0              1  Aarav                  python sql machine learning excel           0.755230
1              2   Diya         excel communication recruitment onboarding           0.611714
12            13  Advik       project management agile scrum communication           0.506996
8              9  Arjun         manual testing selenium jira communication           0.364811
17            18   Sara  recruitment analytics excel communication hr o...           0.352359

In [78]:
# This cell calculates cosine similarity between:
# 1. the job description vector
# 2. each candidate skill vector
#
# The result is stored as a similarity score for each candidate.

job_vector = tfidf_matrix[0:1]
candidate_vectors = tfidf_matrix[1:]

similarity_scores = cosine_similarity(job_vector, candidate_vectors).flatten()

df["similarity_score"] = similarity_scores

print("Cosine similarity scores calculated successfully.")
df[["candidate_id", "name", "skills", "similarity_score"]]

Cosine similarity scores calculated successfully.

    candidate_id     name                                             skills  similarity_score
0              1    Aarav                  python sql machine learning excel          0.461985
1              2     Diya         excel communication recruitment onboarding          0.246840
2              3    Kabir            python pandas data analysis sql tableau          0.113584
3              4   Ishita             java sql spring communication teamwork          0.128840
4              5   Vivaan                  python sql deep learning nlp bert          0.373774
5              6    Anaya  recruitment sourcing interview screening commu...          0.188620
6              7  Reyansh               python sql power bi excel statistics          0.119317
7              8     Myra  machine learning python data visualization tab...          0.275516
8              9    Arjun         manual testing selenium jira communication          0.061943
9             10     Siya           python sql ml nlp communication teamwork          0.349575
10            11    Krish             excel sql reporting dashboard power bi          0.052342
11            12   Aadhya               python r statistics machine learning          0.382899
12            13    Advik       project management agile scrum communication          0.061943
13            14    Kiara  python sql data analysis recruitment hr analytics          0.406514
14            15   Atharv     c++ algorithms data structures problem solving          0.000000
15            16    Navya          python sql tableau power bi communication          0.204367
16            17    Rudra      nlp bert transformers python machine learning          0.418469
17            18     Sara  recruitment analytics excel communication hr o...          0.364453
18            19   Vihaan         python sql statistics data cleaning pandas          0.109594
19            20    Meera  python machine learning sql communication dash...          0.755230

In [79]:
# Step 7: Normalize Experience and Certifications

from sklearn.preprocessing import MinMaxScaler

# ✅ Check if required columns exist
required_cols = ['experience_years', 'certifications']
for col in required_cols:
    if col not in df.columns:
        raise ValueError(f"Column '{col}' not found in dataset")

# ✅ Handle missing values
df['experience_years'] = df['experience_years'].fillna(0)
df['certifications'] = df['certifications'].fillna(0)

# ✅ Initialize scaler
scaler = MinMaxScaler()

# ✅ Normalize the columns (0 to 1 scale)
df[['Experience_norm', 'Certifications_norm']] = scaler.fit_transform(
    df[['experience_years', 'certifications']]
)

# ✅ Display result
print(df[['experience_years', 'Experience_norm', 'certifications', 'Certifications_norm']].head())

   experience_years  Experience_norm  certifications  Certifications_norm
0                 3              0.4               2             0.333333
1                 4              0.6               1             0.000000
2                 2              0.2               3             0.666667
3                 5              0.8               2             0.333333
4                 6              1.0               4             1.000000

In [80]:
# This cell normalizes experience and certification values.
# Normalization means converting values into a common range.
# Here we divide each value by the maximum value in its column.

df["experience_score"] = df["experience_years"] / df["experience_years"].max()
df["certification_score"] = df["certifications"] / df["certifications"].max()

df[["name", "experience_years", "experience_score", "certifications", "certification_score"]]

       name  experience_years  experience_score  certifications  certification_score
0     Aarav                 3          0.500000               2                 0.50
1      Diya                 4          0.666667               1                 0.25
2     Kabir                 2          0.333333               3                 0.75
3    Ishita                 5          0.833333               2                 0.50
4    Vivaan                 6          1.000000               4                 1.00
5     Anaya                 3          0.500000               2                 0.50
6   Reyansh                 4          0.666667               2                 0.50
7      Myra                 2          0.333333               3                 0.75
8     Arjun                 5          0.833333               1                 0.25
9      Siya                 3          0.500000               3                 0.75
10    Krish                 2          0.333333               2                 0.50
11   Aadhya                 4          0.666667               3                 0.75
12    Advik                 6          1.000000               2                 0.50
13    Kiara                 5          0.833333               4                 1.00
14   Atharv                 1          0.166667               1                 0.25
15    Navya                 3          0.500000               2                 0.50
16    Rudra                 5          0.833333               4                 1.00
17     Sara                 4          0.666667               2                 0.50
18   Vihaan                 2          0.333333               2                 0.50
19    Meera                 4          0.666667               3                 0.75

In [81]:
# Step 8: Assign Education Scores

# ✅ Check if column exists
if 'education' not in df.columns:
    raise ValueError("Column 'education' not found in dataset")

# ✅ Handle missing values
df['education'] = df['education'].fillna('').astype(str)

# ✅ Define education scoring (custom mapping)
education_score_map = {
    "B.Tech": 3,
    "B.Sc": 3,
    "BBA": 3,
    "BCA": 3,
    "B.Com": 3,
    "MBA": 4,
    "MBA HR": 4,
    "M.Sc": 4,
    "M.Tech": 4,
    "MCA": 4,
    "M.Stat": 4
}

# ✅ Convert education into numerical score
df['Education_score'] = df['education'].map(education_score_map)

# ✅ Handle unknown categories (if any)
df['Education_score'] = df['Education_score'].fillna(0)

# ✅ Display result
print(df[['education', 'Education_score']].head())

  education  Education_score
0    B.Tech                3
1    MBA HR                4
2      B.Sc                3
3    B.Tech                3
4    M.Tech                4

In [82]:
# This cell maps education categories into numerical scores.
# Higher values are assigned to higher or more specialized qualifications.
# This is just a teaching example, not a universal hiring rule.

education_map = {
    "B.Com": 0.50,
    "BBA": 0.55,
    "BCA": 0.55,
    "B.Sc": 0.60,
    "B.Tech": 0.70,
    "MBA": 0.75,
    "MBA HR": 0.80,
    "MCA": 0.80,
    "M.Sc": 0.80,
    "M.Tech": 0.90,
    "M.Stat": 0.90
}

df["education_score"] = df["education"].map(education_map)

df[["name", "education", "education_score"]]

       name education  education_score
0     Aarav    B.Tech             0.70
1      Diya    MBA HR             0.80
2     Kabir      B.Sc             0.60
3    Ishita    B.Tech             0.70
4    Vivaan    M.Tech             0.90
5     Anaya    MBA HR             0.80
6   Reyansh    B.Tech             0.70
7      Myra      M.Sc             0.80
8     Arjun       BCA             0.55
9      Siya       MCA             0.80
10    Krish     B.Com             0.50
11   Aadhya    M.Stat             0.90
12    Advik       MBA             0.75
13    Kiara    MBA HR             0.80
14   Atharv    B.Tech             0.70
15    Navya       BBA             0.55
16    Rudra    M.Tech             0.90
17     Sara    MBA HR             0.80
18   Vihaan      B.Sc             0.60
19    Meera       MCA             0.80

In [83]:
# Step 9: Create a Weighted Final Score

from sklearn.metrics.pairwise import cosine_similarity

# ✅ Compute cosine similarity (job description vs resumes)
cosine_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()

# ✅ Add similarity score to dataframe
df['Similarity_score'] = cosine_sim

# ✅ Normalize similarity score (optional but recommended)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['Similarity_score'] = scaler.fit_transform(df[['Similarity_score']])

# ✅ Normalize Education score (if not already normalized)
df['Education_norm'] = df['Education_score'] / df['Education_score'].max()

# ✅ Final Weighted Score Calculation
df['Final_score'] = (
    0.50 * df['Similarity_score'] +
    0.25 * df['Experience_norm'] +
    0.15 * df['Education_norm'] +
    0.10 * df['Certifications_norm']
)

# ✅ Sort candidates by Final Score (highest first)
df = df.sort_values(by='Final_score', ascending=False)

# ✅ Display top candidates
print(df[['Similarity_score', 'Experience_norm', 'Education_norm', 'Certifications_norm', 'Final_score']].head())

    Similarity_score  Experience_norm  Education_norm  Certifications_norm  Final_score
19          1.000000              0.6             1.0             0.666667     0.866667
4           0.494914              1.0             1.0             1.000000     0.747457
16          0.554095              0.8             1.0             1.000000     0.727047
13          0.538264              0.8             1.0             1.000000     0.719132
11          0.506996              0.6             1.0             0.666667     0.620165

In [84]:
# This cell creates the final weighted score for each candidate.
# It combines text similarity, experience, education, and certifications.

df["final_score"] = (
    0.50 * df["similarity_score"] +
    0.25 * df["experience_score"] +
    0.15 * df["education_score"] +
    0.10 * df["certification_score"]
)

df[["name", "similarity_score", "experience_score", "education_score", "certification_score", "final_score"]]

       name  similarity_score  experience_score  education_score  certification_score  final_score
19    Meera          0.755230          0.666667             0.80                 0.75     0.739282
4    Vivaan          0.373774          1.000000             0.90                 1.00     0.671887
16    Rudra          0.418469          0.833333             0.90                 1.00     0.652568
13    Kiara          0.406514          0.833333             0.80                 1.00     0.631590
11   Aadhya          0.382899          0.666667             0.90                 0.75     0.568116
17     Sara          0.364453          0.666667             0.80                 0.50     0.518893
0     Aarav          0.461985          0.500000             0.70                 0.50     0.510992
9      Siya          0.349575          0.500000             0.80                 0.75     0.494788
12    Advik          0.061943          1.000000             0.75                 0.50     0.443472
1      Diya          0.246840          0.666667             0.80                 0.25     0.435087
7      Myra          0.275516          0.333333             0.80                 0.75     0.416091
3    Ishita          0.128840          0.833333             0.70                 0.50     0.427753
5     Anaya          0.188620          0.500000             0.80                 0.50     0.389310
15    Navya          0.204367          0.500000             0.55                 0.50     0.359683
6   Reyansh          0.119317          0.666667             0.70                 0.50     0.381325
8     Arjun          0.061943          0.833333             0.55                 0.25     0.346805
2     Kabir          0.113584          0.333333             0.60                 0.75     0.305125
18   Vihaan          0.109594          0.333333             0.60                 0.50     0.278130
10    Krish          0.052342          0.333333             0.50                 0.50     0.234504
14   Atharv          0.000000          0.166667             0.70                 0.25     0.171667

In [85]:
# Step 10: Rank Candidates

# ✅ Sort candidates by Final Score (highest first)
df_sorted = df.sort_values(by='Final_score', ascending=False)

# ✅ Reset index for clean ranking
df_sorted = df_sorted.reset_index(drop=True)

# ✅ Assign rank (1 = best candidate)
df_sorted['Rank'] = df_sorted.index + 1

# ✅ Display ranked candidates
print(df_sorted[['Rank', 'Final_score']].head(10))

   Rank  Final_score
0     1     0.866667
1     2     0.747457
2     3     0.727047
3     4     0.719132
4     5     0.620165
5     6     0.574620
6     7     0.551690
7     8     0.548103
8     9     0.474343
9    10     0.463420

In [86]:
# This cell sorts candidates in descending order based on the final score.
# The highest-scoring candidate appears first.

ranked_df = df.sort_values(by="final_score", ascending=False).reset_index(drop=True)

ranked_df[["candidate_id", "name", "skills", "experience_years", "education", "certifications", "final_score"]]

    candidate_id     name                                             skills  experience_years education  certifications  final_score
0             20    Meera  python machine learning sql communication dash...                 4       MCA               3     0.739282
1              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4     0.671887
2             17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4     0.652568
3             14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4     0.631590
4             12   Aadhya               python r statistics machine learning                 4    M.Stat               3     0.568116
5             18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2     0.518893
6              1    Aarav                  python sql machine learning excel                 3    B.Tech               2     0.510992
7             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3     0.494788
8             13    Advik       project management agile scrum communication                 6       MBA               2     0.443472
9              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1     0.435087
10             4   Ishita             java sql spring communication teamwork                 5    B.Tech               2     0.427753
11             8     Myra  machine learning python data visualization tab...                 2      M.Sc               3     0.416091
12             6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2     0.389310
13             7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2     0.381325
14            16    Navya          python sql tableau power bi communication                 3       BBA               2     0.359683
15             9    Arjun         manual testing selenium jira communication                 5       BCA               1     0.346805
16             3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3     0.305125
17            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2     0.278130
18            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2     0.234504
19            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1     0.171667

In [87]:
# Step 11: Generate Top 5 Shortlisted Candidates

# ✅ Select top 5 candidates from ranked dataframe
top_5_candidates = df_sorted.head(5)

# ✅ Display shortlisted candidates
print("Top 5 Shortlisted Candidates:\n")
print(top_5_candidates[['Rank', 'Final_score']])

Top 5 Shortlisted Candidates:

   Rank  Final_score
0     1     0.866667
1     2     0.747457
2     3     0.727047
3     4     0.719132
4     5     0.620165

In [88]:
# This cell extracts the top 5 candidates from the ranked dataset.
# These candidates are considered the strongest matches according to the model.

top_5 = ranked_df.head(5)

top_5[["candidate_id", "name", "skills", "experience_years", "education", "certifications", "final_score"]]

   candidate_id    name                                             skills  experience_years education  certifications  final_score
0            20   Meera  python machine learning sql communication dash...                 4       MCA               3     0.739282
1             5  Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4     0.671887
2            17   Rudra      nlp bert transformers python machine learning                 5    M.Tech               4     0.652568
3            14   Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4     0.631590
4            12  Aadhya               python r statistics machine learning                 4    M.Stat               3     0.568116

In [89]:
# Step 12: Add HR Interpretation Labels

# ✅ Function to assign labels based on Final Score
def assign_label(score):
    if score >= 0.75:
        return "Strong Match"
    elif score >= 0.50:
        return "Moderate Match"
    else:
        return "Low Match"

# ✅ Apply function to create new column
df_sorted['HR_Recommendation'] = df_sorted['Final_score'].apply(assign_label)

# ✅ Display results
print(df_sorted[['Rank', 'Final_score', 'HR_Recommendation']].head(10))

   Rank  Final_score HR_Recommendation
0     1     0.866667      Strong Match
1     2     0.747457    Moderate Match
2     3     0.727047    Moderate Match
3     4     0.719132    Moderate Match
4     5     0.620165    Moderate Match
5     6     0.574620    Moderate Match
6     7     0.551690    Moderate Match
7     8     0.548103    Moderate Match
8     9     0.474343         Low Match
9    10     0.463420         Low Match

In [90]:
# This cell converts final numeric scores into simple decision labels.
# This makes the result easier to interpret from an HR point of view.

def label_candidate(score):
    if score >= 0.65:
        return "Strong Match"
    elif score >= 0.50:
        return "Moderate Match"
    else:
        return "Low Match"

ranked_df["recommendation"] = ranked_df["final_score"].apply(label_candidate)

ranked_df[["candidate_id", "name", "final_score", "recommendation"]]

    candidate_id     name  final_score  recommendation
0             20    Meera     0.739282    Strong Match
1              5   Vivaan     0.671887    Strong Match
2             17    Rudra     0.652568    Strong Match
3             14    Kiara     0.631590  Moderate Match
4             12   Aadhya     0.568116  Moderate Match
5             18     Sara     0.518893  Moderate Match
6              1    Aarav     0.510992  Moderate Match
7             10     Siya     0.494788       Low Match
8             13    Advik     0.443472       Low Match
9              2     Diya     0.435087       Low Match
10             4   Ishita     0.427753       Low Match
11             8     Myra     0.416091       Low Match
12             6    Anaya     0.389310       Low Match
13             7  Reyansh     0.381325       Low Match
14            16    Navya     0.359683       Low Match
15             9    Arjun     0.346805       Low Match
16             3    Kabir     0.305125       Low Match
17            19   Vihaan     0.278130       Low Match
18            11    Krish     0.234504       Low Match
19            15   Atharv     0.171667       Low Match

In [91]:
# Step 13: Final Recruitment Output

# ✅ Select important columns for HR review
columns_to_display = [
    'Rank',
    'name' if 'name' in df_sorted.columns else None,
    'Final_score',
    'HR_Recommendation',
    'experience_years',
    'education',
    'certifications'
]

# ✅ Remove None values (if 'Name' column doesn't exist)
columns_to_display = [col for col in columns_to_display if col is not None]

# ✅ Create final output table
final_output = df_sorted[columns_to_display]

# ✅ Display final recruitment table
print("Final Recruitment Output:\n")
print(final_output.head(10))

Final Recruitment Output:

   Rank    name  Final_score HR_Recommendation  experience_years education  certifications
0     1   Meera     0.866667      Strong Match                 4       MCA               3
1     2  Vivaan     0.747457    Moderate Match                 6    M.Tech               4
2     3   Rudra     0.727047    Moderate Match                 5    M.Tech               4
3     4   Kiara     0.719132    Moderate Match                 5    MBA HR               4
4     5  Aadhya     0.620165    Moderate Match                 4    M.Stat               3
5     6    Sara     0.574620    Moderate Match                 4    MBA HR               2
6     7   Aarav     0.551690    Moderate Match                 3    B.Tech               2
7     8    Siya     0.548103    Moderate Match                 3       MCA               3
8     9   Advik     0.474343         Low Match                 6       MBA               2
9    10    Diya     0.463420         Low Match                 4    MBA HR               1

In [92]:
# This cell creates the final structured output table.
# It includes the original candidate details and all calculated scores.

final_output = ranked_df[[
    "candidate_id",
    "name",
    "skills",
    "experience_years",
    "education",
    "certifications",
    "similarity_score",
    "experience_score",
    "education_score",
    "certification_score",
    "final_score",
    "recommendation"
]]

final_output

    candidate_id     name                                             skills  experience_years education  certifications  similarity_score  experience_score  education_score  certification_score  final_score  recommendation
0             20    Meera  python machine learning sql communication dash...                 4       MCA               3          0.755230          0.666667             0.80                 0.75     0.739282    Strong Match
1              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4          0.373774          1.000000             0.90                 1.00     0.671887    Strong Match
2             17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4          0.418469          0.833333             0.90                 1.00     0.652568    Strong Match
3             14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4          0.406514          0.833333             0.80                 1.00     0.631590  Moderate Match
4             12   Aadhya               python r statistics machine learning                 4    M.Stat               3          0.382899          0.666667             0.90                 0.75     0.568116  Moderate Match
5             18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2          0.364453          0.666667             0.80                 0.50     0.518893  Moderate Match
6              1    Aarav                  python sql machine learning excel                 3    B.Tech               2          0.461985          0.500000             0.70                 0.50     0.510992  Moderate Match
7             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3          0.349575          0.500000             0.80                 0.75     0.494788       Low Match
8             13    Advik       project management agile scrum communication                 6       MBA               2          0.061943          1.000000             0.75                 0.50     0.443472       Low Match
9              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1          0.246840          0.666667             0.80                 0.25     0.435087       Low Match
10             4   Ishita             java sql spring communication teamwork                 5    B.Tech               2          0.128840          0.833333             0.70                 0.50     0.427753       Low Match
11             8     Myra  machine learning python data visualization tab...                 2      M.Sc               3          0.275516          0.333333             0.80                 0.75     0.416091       Low Match
12             6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2          0.188620          0.500000             0.80                 0.50     0.389310       Low Match
13             7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2          0.119317          0.666667             0.70                 0.50     0.381325       Low Match
14            16    Navya          python sql tableau power bi communication                 3       BBA               2          0.204367          0.500000             0.55                 0.50     0.359683       Low Match
15             9    Arjun         manual testing selenium jira communication                 5       BCA               1          0.061943          0.833333             0.55                 0.25     0.346805       Low Match
16             3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3          0.113584          0.333333             0.60                 0.75     0.305125       Low Match
17            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2          0.109594          0.333333             0.60                 0.50     0.278130       Low Match
18            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2          0.052342          0.333333             0.50                 0.50     0.234504       Low Match
19            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1          0.000000          0.166667             0.70                 0.25     0.171667       Low Match

In [93]:
# Step 14: Save the Final Output as CSV

# ✅ Save final output to CSV file
final_output.to_csv("final_recruitment_output.csv", index=False)

print("✅ File saved successfully as 'final_recruitment_output.csv'")

✅ File saved successfully as 'final_recruitment_output.csv'

In [94]:
# This cell saves the final recruitment output into a CSV file.
# Students can download the file after running the cell.

final_output.to_csv("recruitment_screening_output.csv", index=False)

print("File saved successfully as recruitment_screening_output.csv")

File saved successfully as recruitment_screening_output.csv

In [95]:
# Step 15: Conclusion

conclusion_text = """
In this lab, we learned how to:
- create a synthetic recruitment dataset
- define a job description
- convert text into numbers using TF-IDF
- calculate candidate-job similarity using cosine similarity
- combine multiple recruitment factors into a weighted score
- rank candidates and generate a shortlist

Important Insight:
This is an AI-assisted recruitment model, not a fully autonomous hiring system.

AI can:
- speed up initial screening
- organize candidate information
- support ranking

But HR must still:
- validate the results
- check fairness and bias
- consider communication, attitude, and role fit
- make the final decision
"""

print(conclusion_text)

In this lab, we learned how to:
- create a synthetic recruitment dataset
- define a job description
- convert text into numbers using TF-IDF
- calculate candidate-job similarity using cosine similarity
- combine multiple recruitment factors into a weighted score
- rank candidates and generate a shortlist

Important Insight:
This is an AI-assisted recruitment model, not a fully autonomous hiring system.

AI can:
- speed up initial screening
- organize candidate information
- support ranking

But HR must still:
- validate the results
- check fairness and bias
- consider communication, attitude, and role fit
- make the final decision